In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl

In [3]:
df = pd.read_csv('./csv_files/result_summary.csv')
df

,username,name,kd,binding_strength,binding,expression,sequence,dna,pae_interaction,esm_pll,iptm,plddt,similarity_check,design_models
0,Cradle,round1zeroshot.K5Q_N70S_K71R_N73T_S87T_N88D_R1...,1.207153e-09,strong,true,high,QVQLQQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,ATGCAGGTGCAGCTGCAGCAGAGCGGCCCGGGCCTGGTTCAACCAT...,13.582976,-301.252145,0.92,90.465145,0.958000,"[""Custom PLM""]"
1,Tihumab,chrisxushaoyong.hu_nano2_4_85252b,5.183041e-09,strong,true,high,EVQLLESGGGVVKPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,ATGGAAGTGCAGCTGCTGGAAAGCGGCGGCGGCGTGGTGAAACCAG...,27.060766,-145.413214,0.21,77.194016,0.921000,"[""Custom PLM""]"
2,NaN,Cetuximab_scFv,6.638345e-09,strong,true,low,QVQLKQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,ATGCAGGTGCAGCTGAAACAGAGCGGCCCGGGCCTGGTGCAGCCAT...,NaN,NaN,NaN,NaN,NaN,NaN
3,Tihumab,chrisxushaoyong.hu_nano2_2_7ef96e,1.795552e-08,strong,true,high,EVQLLESGGGVVRPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,ATGGAAGTGCAGCTGCTGGAAAGCGGCGGCGGCGTTGTTCGTCCAG...,27.464363,-153.332953,0.21,75.850000,0.913000,"[""Custom PLM""]"
4,Aurelia Bustos,aureliabustos.bce_var433,5.157577e-08,medium,true,high,VKGHFAECPEQYKHYCIHGTCRYVIAENTPSCVCDEGYIGARCERV...,ATGGTGAAAGGCCATTTTGCGGAATGCCCGGAACAGTATAAACATT...,7.931915,-69.710619,0.94,90.466400,0.799680,"[""ProteinMPNN/LigandMPNN""]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,colby,"colby.TUPEGFR_006___anti-EGFR,_Fv-like_protein...",NaN,unknown,unknown,none,QAQTQESGPGTVEPGGTVKLSCTAAGFSTSDGNRWMHWVRRHPGQA...,ATGCAGGCGCAGACCCAGGAAAGCGGCCCGGGTACTGTTGAACCAG...,21.668666,-536.510982,0.49,65.504280,0.521136,"[""Custom ensemble/diffusion""]"
398,x.rustamov,x.rustamov.traj_6_1_model_1_8,NaN,unknown,unknown,none,TKRVDVTGDTAVKEGSTFTATGTASGFYTAVYSISWYAESAERGRV...,ATGACCAAACGCGTGGATGTGACCGGCGATACCGCGGTGAAAGAAG...,27.976872,-275.182328,0.23,74.987731,0.352836,"[""AlphaFold2""]"
399,colby,"colby.TUPEGFR_018___anti-EGFR,_Fv-like_protein...",NaN,unknown,unknown,none,QVQLKQSGPGLVQPSQSLSITCTVSGFDLTDYGVNWVRQSPGKGLE...,ATGCAGGTGCAGCTGAAACAGAGCGGCCCGGGCCTGGTGCAGCCAT...,25.893594,-293.600595,0.32,81.808080,0.809172,"[""Custom ensemble/diffusion""]"
400,eureka,xiuming_li2015.Eureka_seq_1,NaN,unknown,unknown,none,QVQLKESGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,ATGCAGGTGCAGCTGAAAGAAAGCGGCCCGGGCCTGGTGCAGCCGT...,16.679623,-294.362538,0.89,91.698133,0.958000,"[""Custom PLM""]"
401,ZhouZhouZhou,724928537.DBZ7___A,NaN,unknown,unknown,none,QVQLVESGGGLVQPGGSLRLSCAASGYTFTEYPLGWFRQAPGQGLE...,ATGCAGGTGCAGCTGGTGGAAAGCGGCGGCGGCTTAGTGCAACCAG...,25.686534,-105.734617,0.27,75.533193,0.816000,"[""Custom PLM""]"

In [5]:
df2 = pd.read_csv('./csv_files/proteinbase_collection_adaptyv-egfr-competition-round-2.csv')
df2

,id,name,sequence,author,designMethod,evaluations
0,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,"[{""type"":""experimental"",""value"":{""url"":""https:..."
1,silver-crow-birch,s1995825.cotimed_egf_netsolp_usability_4,TCPEEYSGYCLHNAKCYYIEALNDVGCQCVKGFVGPRCAFKNLNEGN,wellswoodlab,co-timed,"[{""type"":""experimental"",""value"":false,""metric""..."
2,amber-boar-snow,tadaskluonis.cotimed_egf_BCseq_1,TCPAYYKGYCLNNARCYYITVLNDVGCQCQKGFDGGRCAFVNLLLDV,tadas-kluonis-cww,co-timed,"[{""type"":""experimental"",""value"":false,""metric""..."
3,swift-fox-ice,s1995825.cotimed_egf_netsolp_usability_6,TCPAYYKGYCLHNAKCYYIEALNDVGCQCQKGFVGPRCSFKNLNENN,wellswoodlab,co-timed,"[{""type"":""experimental"",""value"":false,""metric""..."
4,jade-deer-cedar,biolucasmachado.engineered_binder_6,SYFTPCGPEFNGYCVHGECRYVALLNQVACICHDGWTGERCELPDL...,biolucasmachado,esm2-optimization,"[{""type"":""experimental"",""value"":true,""metric"":..."
...,...,...,...,...,...,...
395,amber-bear-plume,duynth29.L88_MPNN5,ALTEGEKQVIRQLEIYNTWVLQELEEIEKRYIETKKEEDLQEFEIL...,duynth29,bindcraft,"[{""type"":""experimental"",""value"":true,""metric"":..."
396,noble-raven-leaf,martin.EGFR_l121_s46924_mpnn18,AGLTTEEKYAVLEFEYGDLEVHVVFWFEITFDENGKVVGAEMKGGL...,martin-pacesa,bindcraft,"[{""type"":""experimental"",""value"":true,""metric"":..."
397,steady-panther-rose,alecl.unrelaxedA,AESHFSECPASLQNFCQNGTCRFHVGLNQPACICNRGYIGSRCELR...,alecl,NaN,"[{""type"":""experimental"",""value"":true,""metric"":..."
398,green-quail-lotus,tarkhov.andrey.Erithacus_rubecula_gigantus_4,AEAVAAEAAEGGEDPFASLAERAADDPCAGGRDGSCAAPPYIFLAA...,erithacus-rubecula,NaN,"[{""type"":""experimental"",""value"":true,""metric"":..."
399,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,"[{""type"":""experimental"",""value"":true,""metric"":..."

**Changing design method column so that it doesn't have square brackets**

In [6]:
import ast
df['design_models'] = df['design_models'].apply(lambda x: ast.literal_eval(x)[0] if isinstance(x, str) and len(ast.literal_eval(x)) > 0 else None)
df

,username,name,kd,binding_strength,binding,expression,sequence,dna,pae_interaction,esm_pll,iptm,plddt,similarity_check,design_models
0,Cradle,round1zeroshot.K5Q_N70S_K71R_N73T_S87T_N88D_R1...,1.207153e-09,strong,true,high,QVQLQQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,ATGCAGGTGCAGCTGCAGCAGAGCGGCCCGGGCCTGGTTCAACCAT...,13.582976,-301.252145,0.92,90.465145,0.958000,Custom PLM
1,Tihumab,chrisxushaoyong.hu_nano2_4_85252b,5.183041e-09,strong,true,high,EVQLLESGGGVVKPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,ATGGAAGTGCAGCTGCTGGAAAGCGGCGGCGGCGTGGTGAAACCAG...,27.060766,-145.413214,0.21,77.194016,0.921000,Custom PLM
2,NaN,Cetuximab_scFv,6.638345e-09,strong,true,low,QVQLKQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,ATGCAGGTGCAGCTGAAACAGAGCGGCCCGGGCCTGGTGCAGCCAT...,NaN,NaN,NaN,NaN,NaN,None
3,Tihumab,chrisxushaoyong.hu_nano2_2_7ef96e,1.795552e-08,strong,true,high,EVQLLESGGGVVRPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,ATGGAAGTGCAGCTGCTGGAAAGCGGCGGCGGCGTTGTTCGTCCAG...,27.464363,-153.332953,0.21,75.850000,0.913000,Custom PLM
4,Aurelia Bustos,aureliabustos.bce_var433,5.157577e-08,medium,true,high,VKGHFAECPEQYKHYCIHGTCRYVIAENTPSCVCDEGYIGARCERV...,ATGGTGAAAGGCCATTTTGCGGAATGCCCGGAACAGTATAAACATT...,7.931915,-69.710619,0.94,90.466400,0.799680,ProteinMPNN/LigandMPNN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,colby,"colby.TUPEGFR_006___anti-EGFR,_Fv-like_protein...",NaN,unknown,unknown,none,QAQTQESGPGTVEPGGTVKLSCTAAGFSTSDGNRWMHWVRRHPGQA...,ATGCAGGCGCAGACCCAGGAAAGCGGCCCGGGTACTGTTGAACCAG...,21.668666,-536.510982,0.49,65.504280,0.521136,Custom ensemble/diffusion
398,x.rustamov,x.rustamov.traj_6_1_model_1_8,NaN,unknown,unknown,none,TKRVDVTGDTAVKEGSTFTATGTASGFYTAVYSISWYAESAERGRV...,ATGACCAAACGCGTGGATGTGACCGGCGATACCGCGGTGAAAGAAG...,27.976872,-275.182328,0.23,74.987731,0.352836,AlphaFold2
399,colby,"colby.TUPEGFR_018___anti-EGFR,_Fv-like_protein...",NaN,unknown,unknown,none,QVQLKQSGPGLVQPSQSLSITCTVSGFDLTDYGVNWVRQSPGKGLE...,ATGCAGGTGCAGCTGAAACAGAGCGGCCCGGGCCTGGTGCAGCCAT...,25.893594,-293.600595,0.32,81.808080,0.809172,Custom ensemble/diffusion
400,eureka,xiuming_li2015.Eureka_seq_1,NaN,unknown,unknown,none,QVQLKESGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,ATGCAGGTGCAGCTGAAAGAAAGCGGCCCGGGCCTGGTGCAGCCGT...,16.679623,-294.362538,0.89,91.698133,0.958000,Custom PLM
401,ZhouZhouZhou,724928537.DBZ7___A,NaN,unknown,unknown,none,QVQLVESGGGLVQPGGSLRLSCAASGYTFTEYPLGWFRQAPGQGLE...,ATGCAGGTGCAGCTGGTGGAAAGCGGCGGCGGCTTAGTGCAACCAG...,25.686534,-105.734617,0.27,75.533193,0.816000,Custom PLM

**Filtering relevant columns**

In [7]:
cols_to_keep = ['name', 'binding', 'expression', 'sequence', 'design_models']
df_filtered = df[cols_to_keep]
df_filtered

,name,binding,expression,sequence,design_models
0,round1zeroshot.K5Q_N70S_K71R_N73T_S87T_N88D_R1...,true,high,QVQLQQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,Custom PLM
1,chrisxushaoyong.hu_nano2_4_85252b,true,high,EVQLLESGGGVVKPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,Custom PLM
2,Cetuximab_scFv,true,low,QVQLKQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,None
3,chrisxushaoyong.hu_nano2_2_7ef96e,true,high,EVQLLESGGGVVRPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,Custom PLM
4,aureliabustos.bce_var433,true,high,VKGHFAECPEQYKHYCIHGTCRYVIAENTPSCVCDEGYIGARCERV...,ProteinMPNN/LigandMPNN
...,...,...,...,...,...
397,"colby.TUPEGFR_006___anti-EGFR,_Fv-like_protein...",unknown,none,QAQTQESGPGTVEPGGTVKLSCTAAGFSTSDGNRWMHWVRRHPGQA...,Custom ensemble/diffusion
398,x.rustamov.traj_6_1_model_1_8,unknown,none,TKRVDVTGDTAVKEGSTFTATGTASGFYTAVYSISWYAESAERGRV...,AlphaFold2
399,"colby.TUPEGFR_018___anti-EGFR,_Fv-like_protein...",unknown,none,QVQLKQSGPGLVQPSQSLSITCTVSGFDLTDYGVNWVRQSPGKGLE...,Custom ensemble/diffusion
400,xiuming_li2015.Eureka_seq_1,unknown,none,QVQLKESGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,Custom PLM
401,724928537.DBZ7___A,unknown,none,QVQLVESGGGLVQPGGSLRLSCAASGYTFTEYPLGWFRQAPGQGLE...,Custom PLM

**Make sure to not have any spaces**

In [8]:
df_filtered.loc[:, "design_models"] = df_filtered["design_models"].str.replace(" ", "_")
df_filtered

,name,binding,expression,sequence,design_models
0,round1zeroshot.K5Q_N70S_K71R_N73T_S87T_N88D_R1...,true,high,QVQLQQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,Custom_PLM
1,chrisxushaoyong.hu_nano2_4_85252b,true,high,EVQLLESGGGVVKPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,Custom_PLM
2,Cetuximab_scFv,true,low,QVQLKQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,None
3,chrisxushaoyong.hu_nano2_2_7ef96e,true,high,EVQLLESGGGVVRPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLE...,Custom_PLM
4,aureliabustos.bce_var433,true,high,VKGHFAECPEQYKHYCIHGTCRYVIAENTPSCVCDEGYIGARCERV...,ProteinMPNN/LigandMPNN
...,...,...,...,...,...
397,"colby.TUPEGFR_006___anti-EGFR,_Fv-like_protein...",unknown,none,QAQTQESGPGTVEPGGTVKLSCTAAGFSTSDGNRWMHWVRRHPGQA...,Custom_ensemble/diffusion
398,x.rustamov.traj_6_1_model_1_8,unknown,none,TKRVDVTGDTAVKEGSTFTATGTASGFYTAVYSISWYAESAERGRV...,AlphaFold2
399,"colby.TUPEGFR_018___anti-EGFR,_Fv-like_protein...",unknown,none,QVQLKQSGPGLVQPSQSLSITCTVSGFDLTDYGVNWVRQSPGKGLE...,Custom_ensemble/diffusion
400,xiuming_li2015.Eureka_seq_1,unknown,none,QVQLKESGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLE...,Custom_PLM
401,724928537.DBZ7___A,unknown,none,QVQLVESGGGLVQPGGSLRLSCAASGYTFTEYPLGWFRQAPGQGLE...,Custom_PLM

**Convert to a FASTA File**

In [ ]:
def df_to_fasta(df, name_col="id", seq_col="sequence", output="sequences.fasta"):
    with open(output, "w") as f:
        for _, row in df.iterrows():
            name = str(row[name_col]).strip().replace("-", "_")
            seq = str(row[seq_col]).strip()
            if pd.notna(name) and pd.notna(seq):
                f.write(f">{name}\n{seq}\n")

In [4]:
df_to_fasta(df2, name_col='id', seq_col='sequence', output='contest_2_round_2_sequences.fasta')

*Quick inspection of FASTA file**

In [23]:
with open("sequences.fasta") as f:
    print(f.read())

>round1zeroshot.K5Q_N70S_K71R_N73T_S87T_N88D_R179K_K183R_E213D_S214P
QVQLQQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLEWLGVIWSGGNTDYNTPFTSRLSISRDTSKSQVFFKMNSLQTDDTAIYYCARALTYYDYEFAYWGQGTLVTVSAGGGGSGGGGSGGGGSDILLTQSPVILSVSPGERVSFSCRASQSIGTNIHWYQQRTNGSPKLLIRYASESISGIPSRFSGSGSGTDFTLSINSVDPEDIADYYCQQNNNWPTTFGAGTKLELK
>chrisxushaoyong.hu_nano2_4_85252b
EVQLLESGGGVVKPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLEWVSAINWSSGSTYYADSVKGRFTISRDDAKNSLYLQMNSLRAEDTAVYYCAAGYQINSGNYNFKDYEYDYWGQGTLVTVSS
>Cetuximab_scFv
QVQLKQSGPGLVQPSQSLSITCTVSGFSLTNYGVHWVRQSPGKGLEWLGVIWSGGNTDYNTPFTSRLSINKDNSKSQVFFKMNSLQSNDTAIYYCARALTYYDYEFAYWGQGTLVTVSAGGGGSGGGGSGGGGSDILLTQSPVILSVSPGERVSFSCRASQSIGTNIHWYQQRTNGSPRLLIKYASESISGIPSRFSGSGSGTDFTLSINSVESEDIADYYCQQNNNWPTTFGAGTKLELK
>chrisxushaoyong.hu_nano2_2_7ef96e
EVQLLESGGGVVRPGGSLRLSCAASGRTFSSYAMGWFRQAPGKGLEWVVAINWSSGSTYYADSVKGRFTISRDDAKNSLYLQMNSLRAEDTALYYCAAGYQINSGNYNFKDYEYDYWGQGTQVTVSS
>aureliabustos.bce_var433
VKGHFAECPEQYKHYCIHGTCRYVIAENTPSCVCDEGYIGARCERVDLFA
>aureliabustos.bce_var464
MKGHFAECPEQYKHYCIHGKCRYVIAENTPSCVCDEGYIGARCERVDLFA
>jvogt4.vogt_scFV_2470
QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAISWVRQAPGQGLEWMGGIIPIFGIANYAQKFQGRVTITADKSTSTAYMELSSLRSEDTAVYYCAREEGPYCSSTSCYAAFDIWGQGTLVTVSSGGGGSGGGGSGGGGSSELTQDPAVSVALGQTVKITCQGDSLRSYFASWYQQKPGQAPTLVIYARNDRPAGIPDRFSGSKSGTSASLAITGLQSEDEADYYCAAWDDSLNGYLFGTGTKLTVL
>lennart.nickel.EGFR_l179_s82283_mpnn1
APPPLYTLEIVLEELLTEALKTYFNTDYRVKVVITFTYEPDLVIRKVEAEGYLYDKNGNEFPKGEGSPFRSWPFVNMLDDHTFEVLMVMDIKLSDDKTVDMVVSLKVTLRKEGDKLIINVETEIVLMDEETKKEYHLKAKGTLTIEGEGKIKVTYVTEPGVTDDGKKVTPEKTIVKEIE
>aureliabustos.bce_var702
EKGHFKECPEQYKHYCIHGTCRYVIAENTPSCVCDEGYIGARCERVDLFA
>jvogt4.vogt_scFV_0128
EVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAISWVRQAPGQGLEWMGGIIPIFGIANYAQKFQGRVTITADKSTSTAYMELSSLRSEDTAVYYCAREEGPYCSSTSCYAAFDIWGQGTMVTVSSGGGGSGGGGSGGGGQSELTQDPAVSVALGQTVKITCQGDSLRSYFASWYQQKPGQAPTLVIYARNDRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCAAWDDSLNGYLFGTGTKVTVL
>jvogt4.vogt_scFV_2009
QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAIGWVRQAPGQGLEWMGGIIPIFGIANYAQKFQGRVTITADKSTSTAYMELSSLRSEDTAVYYCAREEGPYCSSTSCYAAFDIWGQGTMVTVSSGGGGSGGGGSGGGGSSELTQDPAVSVALGQTVKITCQGDSLRSYFASWYQQKPGQAPTLVIYARNDRPSGIPDRFSGSKSGTSASLAISGLQPEDEADYYCAAWDDSLNGYLFGTGTKVTVL
>briannaughton.1_plus_EGFR
SPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSFGGGGGGGGGGGGNSDSECPLSHDGYCLHDGVCMYIEALDKYACNCVVGYIGERCQYRDLKWWELR
>alan.blakely.12_6
SPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSFGGGSGGGSGGGSGGGSGGGSGGGSGGGSGGGSSVVEEYRKLLSKNITTEEEKKKLKELGDKVLAAGDETLGAVVEKEKKILDIIEQEEKE
>chrisxushaoyong.hu_nano1_3_eef94e
EVKLLESGGGSVQTGGSLRLSCAASGRTSRSYGMGWFRQAPGKELEWVSGISWRGDSTGYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAAAAGSAWYGTLYEYDYWGQGTLVTVSS
>begonia.sp.13.EGFR_l88_s11832_mpnn1_model2
EKDPDVVQFEEEVELLKERFKDYPKEVQEKFEEEVEEARKKVEEAYERWKQGIPPPSEYPKLSPHYITWEQVFILHVKAADLDEEYKK
>kurumida.yoichi.mg_05
KIKFLEEIEIDGKKFKILYIEDINEIAVKASDTSATPEQIQKAIEKAK
>alan.blakely.12_3
SPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSFGGGSGGGSGGGSGGGSGGGSGGGSGGGSGGGSDVKKEFRKLLSKNITTQEELEKLKELIEKVLAAGDETLGAVAEKELKIIDIIEEEKKK
>youngsuko2000.queen
NNLYKRCAQSHDGYCLHDGVCMYIEALDKYACNCVVGYIGERCQYRDLKWWWREES
>briannaughton.2_plus_1
SAGQAQIEEVKARADKAKTLEELKELRKEAYEKNWKAYMAVVDETEKKIAEAKATGKGDLDKISEEGNNALQANQNTYLEQWDIIDEKAKELRAAEEAAKGGGGGGGGGGGGSPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSF
>briannaughton.1_plus_2
SPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSFGGGGGGGGGGGGSAGQAQIEEVKARADKAKTLEELKELRKEAYEKNWKAYMAVVDETEKKIAEAKATGKGDLDKISEEGNNALQANQNTYLEQWDIIDEKAKELRAAEEAAK
>alan.blakely.16_2
SPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSFGGGSGGGSGGGSGGGSGGGSGGGSGGGSGGGSSLSEEELEAYIEKKLEEAKKKPASELIEETAKKGESVKLLVLIMLRAEEKNETAKKTLTAEIRELL
>stocco.filippo.1.3.3.18_4_2_iteration0_1.0407930462953479
PENYKSCPPSHDGYCLHGGVCMYISALQAYACNCIQGFVGERCQHSDLEWWE
>stocco.filippo.1.3.3.18_65_0_iteration3_1.028317065130863
PDTIASCPSSHESYCLYQGVCFYFPEMESYACNCVSGYMGERCQFSDLQWWELQ
>chuh.EGFR_Seg2_l58_s53469_mpnn1
NPEIKKLHEEYHELQWKFWAEMSKAFDAGDDKKIEELVEENVKRTEEIFARMDEVEAS
>jvogt4.vogt_scFV_2143
QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAIGWVRQAPGQGLEWMGRIIPIFGIANYAQKFQGRVTITADKSTSTAYMELSSLRSEDTAVYYCAREEGPYCSSTSCYAAFDIWGQGTLVTVSSGGGGSGGGGSGGGGQSVLTQDPAVSVALGQTVKITCQGDSLRSYFASWYQQKPGQAPTLVIYARNDRPSGIPDRFSGSKSGTSASLAITGLQSEDEADYYCAAWDDSLNGYLFGTGTKVTVL
>julian.faust.Pimurutamab_mpnn_17_scfv
EVQLVESGGGLVQPGGSLRLSCAASGFSLNDRAVHWVRQAPGKGLEWLGAIWSGGNTDYGNEFTSRFTISRDNAKNSLYLQMNSLRAEDTAVYYCAVPEDYYGYAFAYWGQGTMVTVSSGGGGSGGGGSGGGGSGGGGSEIVLTQSPATLSLSPGERATLSCRASQSIGTNIHWYQQKPGQAPRLLIKYASESISGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQQNNNWPTSFGGGTKVEIK
>youngsuko2000.ysar
YSAVRRCERSHDGYCLHDGVCMYIEALDKYACNCVVGYIGERCQYRDLKWIAGLII
>Human_EGF
NSDSECPLSHDGYCLHDGVCMYIEALDKYACNCVVGYIGERCQYRDLKWWELR
>stocco.filippo.1.3.3.18_40_0_iteration12_1.0321554292304749
PSTVESCPLSHEGYCLYEGVCFYFPEMESYACNCVSGYMGERCQFSDLEWLELQ
>a.tucs.Andrejs_Tucs_seq5
ECPSEYAGYCLNGGKCVYISALNTYACNCVPGWVGERCEYRDFLADE
>a.tucs.Andrejs_Tucs_seq3
NCPSEFEGYCLNGGTCIYISSLNKYACNCQPGYTGERCEYPDLLASE
>a.tucs.Andrejs_Tucs_seq8
ECGPEYEGYCLNGGTCLYIKKLNKYACNCPVGYVGERCEYVDLLANE
>aureliabustos.wwt_noised_I_scaffold_shorted_var8423
PEILPCPPEHDGYCLHGGTCMYIKALNKVACNCVVGYIGERCQYRDLSRPD
>aureliabustos.wwt_noised_I_scaffold_shorted_var7524
PEILPCPPEHDGYCLHGGTCMYITALNKIACNCVVGYIGERCQYRDLSRPD
>aureliabustos.wwt_noised_I_scaffold_shorted_var9391
PTILPCPPEHDGYCLHGGTCMYITALNKVACNCVVGYIGERCQYRDLSRPE
>aureliabustos.wt_noised_I_scaffold_shorted_var71
PKLLPCPPEHDGYCLHGGTCMYIEALNKIACNCVVGYIGERCQYRDLSAPE
>briannaughton.EGFR_plus_EGFR
NSDSECPLSHDGYCLHDGVCMYIEALDKYACNCVVGYIGERCQYRDLKWWELRGGGGGGGGGGGGGGGGGGGGNSDSECPLSHDGYCLHDGVCMYIEALDKYACNCVVGYIGERCQYRDLKWWELR
>joaosartori2.c1
SHFSECPDEYRHYCFHGTCRWLVIEAKPTCVCHSGYIGARCEHADLEAVVLSSRHRVW
>julian.faust.Pimurutamab_mpnn_18_scfv
EVQLVESGGGLVQPGGSLRLSCAASGFSLTDRAVHWVRQAPGKGLEWLGSIWSGGNTDYGNEFTSRFTISRDNAKNSLYLQMNSLRAEDTAVYYCAVAEDYYGYAFAYWGQGTMVTVSSGGGGSGGGGSGGGGSGGGGSEIVLTQSPATLSLSPGERATLSCRASQSIGTNIHWYQQKPGQAPRLLIKYASESISGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQQNNNWPTSFGGGTKVEIK
>a.tucs.Andrejs_Tucs_seq1
SCPESLKGYCLNDGECIYIEKLNVIACRCQVGWVGERCEYLDLLYNE
>aureliabustos.wwt_noised_I_scaffold_shorted_var6640
PEILPCPPEHDGYCLHGGKCMYITALNKIACNCVVGYIGERCQYRDLSRPE
>kerrding.seq5
SVDEECPESYDGYCLNGGTCVYLETLDSYACRCAEGYVGERCEHKDLDWWEEQ
>deepsatflow.6aru_final_chain_A_domain_3_l142_s806907_mpnn1
QLETEVLGLIPDDAHFEPLKEFVLKYIEILKESEKKLLAGESAEKVLEEAKKKIDEALDEMFAKIPPKHTWEVFFFLMSVVHYISRWYIKIAEEKAEKYKNIDPELAKKYKEFAELVKELEEYVNERALEKAQEGEKKMEEE
>a.tucs.Andrejs_Tucs_seq7
SCPSSYEGYCLNDGTCIYHENLNKYGCRCVPGYYGERCEYLDLTLND
>s1995825.cotimed_egf_netsolp_usability_5
TCPEEYNGYCLNNAKCYYLKALNDVGCQCQKGFVGPRCAFKNLNENN
>kerrding.seq6
SVDEECPESYDGYCLNGGTCVYLEELDSYACRCPEGYIGERCEYKDLDWWEEQ
>briannaughton.2_plus_2
SAGQAQIEEVKARADKAKTLEELKELRKEAYEKNWKAYMAVVDETEKKIAEAKATGKGDLDKISEEGNNALQANQNTYLEQWDIIDEKAKELRAAEEAAKGGGGGGGGGGGGGGGGGGGGGGGGGGGGSAGQAQIEEVKARADKAKTLEELKELRKEAYEKNWKAYMAVVDETEKKIAEAKATGKGDLDKISEEGNNALQANQNTYLEQWDIIDEKAKELRAAEEAAK
>jvogt4.vogt_scFV_2279
QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAIGWVRQAPGQGLEWMGRIIPIFGIANYAQKFQGRVTITADKSTSTAYMELSSLRSEDTAVYYCAREEGPYCSSTSCYAAFDIWGQGTMVTVSSGGGGSGGGGSGGGGSSELTQDPAVSVALGQTVKITCQGDSLRSYFASWYQQKPGQAPTLVIYARNDRPAGVPDRFSGSKSGTSASLAITGLQSEDEADYYCAAWDDSLNGYLFGAGTKVTVL
>gitter.yolo48
APLTEYEKKIEELWDVVHNVPDMEVRRKAIDLVFDLQVTHKITEEQKKEFEEILKEAKEALAK
>alejandro.corrochano-navarro.eng_scfv_binder_2
QVQLKQSGPGLVQPSQSLSITCTVSGFSLTDYWVHWVRQSPGKGLEWLGVIYNDGSTDYNTPFTSRLSINKDNSKSQVFFKMNSLQSNDTAIYYCARALTYYDYEFAYWGQGTLVTVSAGGGGSGGGGSGGGGSDILLTQSPVILSVSPGERVSFSCRASQSIGTNIHWYQQRTNGSPRLLIKNADESIDGIPSRFSGSGSGTDFTLSINSVESEDIADYYCQQSGSWPITFGAGTKLELK
>colby.TUPEGFR_012___anti-EGFR,_Fv-like_protein,_diffused_with_EvoDiff
QVQLEEPDPGVVKDNESLHLTAAVSGYSLTSGERSQHIIHESPDKGLEADGKSAYAENTDGYNNTVTSRFTISVVNSKNVFAVTINSVAQNDSAVYYAARANANYEPYVSKDTAFDYKGQATTITSSSGGGGGGGGGGEIQMNEAADHRAVTAGFEANISCRGERSIGHSKSASGIGWFFQKTGQTLQFLIYYTGERATGIPSRLSGYRDNTKPTLTICSAEAPDAAAYYANYYNEHPPNFGAGTLPVIK
>paulafcfranklin.synth_rosetta_1
SHFSECPDTHRHFCFHGTCRFLLLENKPACICHPGYVGARCEEADLLAVVAAS
>biolucasmachado.engineered_binder_1
SHFSKCPDSYNGYCVHGKCRFYELENKVSCVCDRGWTGERCELPDLLAIVAVVGASVV
>mosquitolkfo.nAb_design_3
FVQLYESGGGLVQWGGSLRLSCAASGRTFSSYAMGWFRQAPGKERLFVVAINWSSGSTYYQDYVKGRFTISRENAKYTMYLQMNMLKPEDTAVYYCAAGYQINSGNYNFKDYEYDYWGQGTQVVVMS
>deepsatflow.6aru_final_chain_A_domain_3_l147_s945609_mpnn1
SATEKIIKASDTANRVLDKLILHIWSNPLITLKELKEFLESHDLDKFFDSLLEVARGAAEAAKTEEAKKKAEEALELLEKIKEMVKNPEKYTIEEVFKLMEEAGELLREVAEDPGMDEKAKEAIKWVGENLRLAAHNYFMLRDYYNE
>aswini.seed1
PSFSICPSNYDSYCLNGGQCFLAEIIHGYTCQCRSGYSGGRVETFDQIYE
>minji.lee.111
MKKKYPVKAKITWSGGNTDERIIGYVEAEKEEDVPFLEITIPDEKYYDYEYLLKYGKIKEIKK
>allongoldberg.3_52_1_refined
LRERLIELLRQLLEEGWGTEEEREWIEERIAILEEGPEPEIVEWWLRAIEWRLAD
>qxy615.s1_rfd_base_46_94
EIVIELPGVTITLYRIEALDKYACRVEVKPGVTVEDLTVEVDGLTIEIRRDLKWWEGYEVRVIE
>elian.elian2
SAGQAVHDYVKARADKPKTLEELKELRKEAYESVWKAYMAVVDETEKKIAEAKATGKGDAGKISEEGANALKTLQNTYKDTADIIDEKAKELRAAEEAAK
>klima.jason.8HGO_design_4yyaf_0_0
ECPLSHDGYCLHDGVCMYIESLSEEEQKKNLIKTLKTHAENIKRALEKLVTPEEAKEANKFIDEIKELLDDPSKEEEVLELVENNKLPVVKEYFKKLSGKYACNCVVGYIGSHPAAQTQSSGGRCQYRDLKWWE
>enzo.morro.design_0_n_0_mpnn_1.117_plddt_0.713_i_ptm_0.082_i_pae_27.542_rmsd_25.669
SMSIEEIFESHISSLVFLKKEETPDKLIYYYKDRKTGKIWKLTVKKSDKTLKTKPITIKIDPDKEIEVEIETELSEEDKEYEPLLKELSENAVEVILKMMKGPLKESLEAILERSKLTGKSVSFSYITFREVNGKKKCFLVTLSIKVKEDGTIEISVEVKEATVSEL
>enzo.morro.design_0_n_1_mpnn_1.085_plddt_0.817_i_ptm_0.076_i_pae_28.084_rmsd_25.372
MKTIVEIFEENIESLVFLKIEKTEDETIYYLKDKKTGRLWKLTVKKSTKAIKSSPATITIDPDKEKKVEIKVELSEEDKKYEPLMKEEQENAVKVILEMMEGPLKETLEALLERSKLTGKEVKLTYITVKEVDGEKKVFVVVISIKVKPDGTVEISVTVYEAEVSEL
>akash.arunabharathi.design4
PLSHDGSGCHEVYQTASGKYACNCVVGYIEKDGKCYRAGLLGWEEAAAKPEAAAKEAAAKPPPEAAAKEAAAKDEEVARVEEVEQLRADLVGRERALTAAATDPAAAAAEIARLRAETTAEIDALRASLSPAAWARYQAAKRAAAAAAEAA
>jack.li.EGFRbindingCandidate_7
QVQLKQSGPGLVQPSQSLSITCTVSGFSVVVYGVHWVRQSPGKGLEWLGVIWSGGNTDYNTPFTSRLSINKDNSKSQVFFKMNSLQSNDTAIYYCARVVVVVVVVVVVWGQGTLVTVSAASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKRVEPK
>christoph.gruber.UpperBinder_Scaffold2_LowerBinder
SEIDEKLKQFLAQLEAEKPENVKKPSDPEVKPSATKEQVVTELARAIAQELGDQKSKEEIAEMALEEYERRLKKKGIELSEEEREKIRELALRAVEEAPTQEQLQQQYKHLQKARE
>nitesh.mishra3.stepwise_scaffold_egfr_binder_6
AECPEEYKNYCKHGTCLYDVKKNKPVCLCDKGYLGPRCEKKDLSLLL
>joaosartori2.c6
SHFSECPESHRGFCFHGTCRLLVNEPTPHCVCHSGYDGARCEHADLAATVLSSDRRVI
>biolucasmachado.engineered_binder_8
SLFSECPESYRGYCVHGTCRHVFLLNQVSCVCHEGWTGERCELPDLLAIVSTTTTTTS
>praghava531.seq2
SPLADLAELAEAAVKAAETEGPAAALAVLREGLAALAARYPEAAGALAAMEAEIAEKKTVDEKLAAGVSALWLLLGALKPEIRKAAYLLAAEILSSDAETALKGLAGVANTAKAFLELEK
>tim.silica_corpora_sampled_epitope_2_generated_variant_9_rank_6_phase_2
EVQLVESGGGLVQPGGSLRLSCAASGSTFSLNVMAWYRQAPGKGRELVAGIISGGSTSYADSVKGRFTISRDNAKNTLYLQMNSLRPEDTAVYYCAHAPVEALLPDTYDYWGQGTLVTVSS
>cameron.kroll.Gertrude_gen6
FEEIKKEIEECEKRAKEIIKELKKLAKEMEKLITEKVDEKTADEAVSILTDMARNILIAVESLANEGYDAIEEGDEETAKELLERLKAFVEEMEKLLKEIKKLAAKATTPEKIKEFVKELQKIKKEVEAMDKEVQDYIDELREKKDK
>klima.jason.8HGO_design_94eja_1_5
ECPLSHDGYCLHDGVCMYIELDDPNFFEKLEKLLEERREAEESEELRRKLEEERRKRRKKLEEELSKKDKKEIKGKYACNCVVGYIGSPGVPTEYAPPYSRCQYRDLKWWE
>areddy.EGFR_l169_s781475
MRHHLANELRRRINGFMTRSYDYMNRRLDRRLREFRSQMARTEPANRKEVGERGMTEFVAVVREIHEKIKEWGDRKLAVIEQLVRQKLSPENAAQVIEKMVKIFQMAFSWMGMFQDFVASYMARMKEFPQYDWPDAIEVAIMMYRFNHHMVWNLFRRRMNNVIADVRGM
>markus.braun.egfr_binder_3
SEKEKKELEENIKLTEEEYETIINALEENKEKLEKLLKEVMELIKAGKVEEAKELVEKELERVKEEYEKAKKTDKEKADKLSVLISFLEGILSNLEKIVDGSDIWDSIMSLYNIAYLASSIDLEIEDQKIKKLLHLARMYKLLGDDEKAQKLFEEAAKLMEEILPKEIEAEREATDFVCEWVGDPAIVAAFRALRDFEIDALERYGPKVIEALKKGEFSDELLAELRAVRAELAERRAAARAAIEAAAAA
>qxy615.s1_rfd_comp_beta_782_81
GTVTLTIKKIEALDKYACSYSADRPLTNADIDALMDAARALGYTLTVLRDLKWWEKYRFRARAKPDLKSATITIE
>kerrding.seq9
AVLEVCPESKEDFCQNDGTCVYNEKEEAYSCECVEGYVGDKCEEIDPDVFEER
>bronte.EGFR_Binder_4_91
EAEVLTRVAKASDAPKVIEELCKELPGPVRVTVTAAGVTETFEGSAEEARIEAINAVSQMKATYGETEVTIEVEPVLL
>merlettaia.seq0v3
QVKLEESGGGSVQTGGSLRLTCAASGRTSRSYGMGWFRQAPGKEREFVSGISWRGDSTGYADSVKGRFTISRDNAKNTVDLQMNSLKPEDTAIYYCAAVKLYNRFTEPTLEPYSFAYWGQGTQVTVSS
>wtj19921231.egfr_binder_design_208_dldesign_0_cycle1_run5_af2pred.pdb_A
KVTLVTSEEALQLLKEQVDGELERKKIELKYKGKSLEERVEAVKKEVEAK
>alessio.daddio.AD_9
SAVDAAAAVFAAKPAEELDRYKILAGSALDYMKHAIRTGLPRQLAAAGHPATDPAELAAMVEALTGALDALVAAALAAAENRAKGGPAVAPAAERAAVEAAARRAAPVVALPGVRDFLREVVARVEELYPEMGAAFAAMVDALIALADAL
>markus.braun.egfr_binder_1
SEIEEAVKKVEEYYKKFKEKLKKDPNATLVGNGSIEEALGAFAVYVTDKCLNAKDLKELIMTLITALHELAHFILGELEDPSVDPEVLKAMVEKAVDLVYDELLKETPKEDTKKRKAIEIFHKAAHHLIEMITLVREGKDLEKAREKLEEFLELLGELIRDLLEGVLSEEEIEELIEVIRELLTAAFELGLKKGFEEFVYLFLESLELIGLLLGYYYQSTTKEDSEYYRELAESLKKVLVKRAKALKEAL
>aswini.seed2_1
GGFQQCIPGYQSYCLNGASCFISEKIEGYTCQCRRGFRGLRCEEEDQEIR
>nicholas-schnicker.schnick_04
MPLSKEEKLEKETKELKEKLEEAKKLVEKGELSVEEQVKLFTELAEKAQKVWDEAIDLGVSKEIYYEAFKVYQDAFWQAVMIVYQS
>maxall4.EGFR_TRIM_l126_s498823_mpnn2_model1_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_top1_mutation_L39G_round1_Chain_A
MEVEELAKGVEIPAEDEDLVTKGMHDLWFLSWLVEQGKGRPVRHMLRHWLEALIDDGYSGSEIYKYIEQSVAKYVEFLKELLKDGMISEEEYEKWLKNLEIIYKMALEVLEELLKERPDLPKPKFP
>paulafcfranklin.synth_rosetta_3
SHFTECPDSYRHFCFHGTCRFLVLENKPACICHPGYVGARCEEADLLAVVASHRTRVA
>paulafcfranklin.synth_rosetta_5
SHFNDCPDTYKHFCFHGTCRFLKLENKPACICHPGYVGARCEEADLLAVVASHTIHKP
>tim.silica_corpora_regions_sampled_epitope_0_generated_variant_6_rank_7_phase_2
EVQLVESGGGLVQAGGSLRLSCAASGRTFSDYIMGWFRQAPGKEREFVVGISWSGGSTYYADSVKGRFTISRDNAKNTMYLQMNSLKPEDTAVYYCAADTYPSYLDDDYAPDDYDYWGQGTQVTVSS
>antorsae.TA_4_4
TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF
>alex.naka.Charmeleon
SYEGYCENGGTLQHIESLDSYTCKCLKGYTGDRCQSQDLRYLYLE
>paulafcfranklin.synth_rosetta_2
SHFTECPEEHRHFCFHGTCRFLPLENKPACICHPGYVGARCEEADLLAVVAS
>stocco.filippo.1.3.3.18_37_0_iteration3_1.024851931427025
SKCPEDLTHYCIHGQCRYIKQQNAPSCRCQHGYIGSRCEYVDLDW
>s1995825.cotimed_egf_netsolp_usability_2
TCPAYYKGYCLNNARCYYIESLNDVGCQCQKGFVGPRCSFKNLNETN
>biolucasmachado.engineered_binder_5
SHFSSCPENYRGYCVHGTCRHSFLLNQVCCVCHKGWTGERCELPDLLAIVSS
>begonia.sp.13.EGFR_l110_s478327_mpnn7_model2
MVLSFEELEKEAREELERRLEEAVEEAYERLLKKGVPEEEAEKFRKLREEEKEVQLMFFGVWLHYLKIVYEIAKKQGRLEEYEKYFREEVEEYIDRAVDVILFPQPGEPL
>elian.elian1
SAGQAVHDSVKARADKAKTLEELKELRKEAYEAVWKAYMAVVDETEKKIAEAKATGKGDAQKISEEGANALRTLQNTYPGFADIIDEKAKELRAAEEAAK
>elian.elian5
SAGQAVHDSVKARADKAKTLEELKELRKEAYEAVWKAYMAVVDETEKKIAEAKATGKGDAQKISEEGANALRTLQNTYPGSADIIDEKAKELRAAEEAAK
>klima.jason.8HGO_design_8gswy_1_2
ECPLSHDGYCLHDGVCMYIENGSGEVKKFSEEEKKELEEKDKEFEKVKEEVDAIRKELEKNKEKTSVEEEIKIEKEAQEKVKEAIKKEMSKYPGNKYACNCVVGYIGSSSLTGGEPGRCQYRDLKWWE
>julie.jg26n
SEVEGIRKSAEQLSKQPDAKTQLENLLQALKDLGAPEEAIKVAQEALEKQ
>qilin_y.test5
GTITLTIKKIEALDKYACAYEADRPITREDEDALMDKARELGYTLTVLRDLKWWEKVIFKAKAKPDLKSATITIE
>julie.ryfqy
EQEKADVINEIAKAGKEKGLSLTEIADKQGEALAGTLEEAKKILEEVKKE
>huiyu.cai.H3_15_3351_H
EVQLVESGGGLVQPGGSLRLSCTVSGFDLTDYGVHWFRQAPGKGLEAVGVIWSGGNTDYNTPFTSRFTISKDNSKNTVYLQMNSLRAEDTAVYYCARQDSPRYPWIPPDYWGQGTLVTVSS
>begonia.sp.13.EGFR_l61_s456546_mpnn1_model1
SDYEKMVALRREVYSLVFQHVVHHGKRPDKEFWEKKLAEVKEKKPEDYELYKKIVEEMMAV
>elian.elian3
SAGQATLDHVKARADKSKTLEELKELRKEAYEDVWKAYMAVVDETEKKIAEAKATGKGDGKKISEEGANALKTLQNTYGSLADIIDEKAKELRAAEEAAK
>lyu.2
SEEEEFIKEVRERAEKAKTLEELKELEREALEKCWSKQMKVIDETEEKIKKAKETGKGDLDKIQEEGTEELEKVKKALLEALDIIQEKAAELRAKEEAAK
>alessio.daddio.AD_1
AAVEEAKAAYAKAKAEYNAIVEPKRKAAEDLTEQANKEKPADKAAAVKAIRQAYSDYVLAEYEAGEILEPAEKALNKAEGELIAEKKAAE
>dre.LGDL_EGFR_008
SLHGQSIYLVDMSQNYSRSEVGYTGVRSEVGYTGVRSE
>noah.holzleitner.Noah_EGFR-Binder_8
MDEDIFNILMENLERLLSRLPEERRPAVRARIAELRARAPTLSDRELIEEANRLMVEIALGE
>salireza111.Seq166_3_002_4
MTDLLIHRAKDAGTPYTVEEIELGDGTILKVAIAGIGGTTAVATELVPK
>pastei5.egfr_binder_01
QMQLSQSGPGLVQPGQSSRITGAVSGFSHMNYGTHWYRQAPRKTLELLAAIWSGGNIDYNDPFKSRLSYNRDNAKSQMPM
>zhoup1366.DBZ7___A
QVQLVESGGGLVQPGGSLRLSCAASGFTFSSYALGWFRQAPGQGLEAVAAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKDLLQVYGMDVWGQGTLVTVS
>cameron.kroll.Gertrude_gen3
FEEIKKEIEECEKRAEEIIRELKKLAKEMEKLITEKVDEKTADEAVSILTDMARNILIAVNSLANEGYSAIEEGDEETAKELLERLKAFVEEMEKLLKEIKKLAAKATTPEKIKEFVKELQKIKKEVEAMDKEVQDYIDELREKKDK
>elian.elian4
SAGQAVLSHVKARADKAKTLEELKELRKEAYESVWKAYMAVVDETEKKIAEAKATGKGDGKKISEEGANALQVLQNTYRPLADIIDEKAKELRAAEEAAK
>cbrown.cbrown_0005_2_EGFR_l81_s801188_mpnn1_model1
MTPEELFEEFVETYFSIQDKLEKTLGPDNPKAKKVYEEMMKIWMRFQHAFWDYLAGGDEEKAKKEMEESIKEIKELAEKNL
>merlettaia.seq6v4
QVQLVESGGGLVQAGGSMRLSCAASGRIFGAYAMGWFRQAPGKEREAVSSISWDEGSTYYADSVKGRFTISRDNAKNTHYLQMSSLKPEDTAVYYCAVRYGLQVNMTMDGYDYWGQGTQVTVSS
>martin.EGFR_l142_s75963_mpnn1
APPPPFEVPGPPEEPQPKFKVEAIYYDSEGNYYEVKAELVFLGSEETPEGTVYYVQIRITAPEKPIKIEEGSILFILAEYDEKTWWIDLPYEDGKIKAWVTEMERGEIYYGEGYAEVSTDAEGKQVVTLYLELRPWKPGEFP
>enzo.morro.design_0_n_2_mpnn_1.120_plddt_0.858_i_ptm_0.072_i_pae_28.117_rmsd_30.276
HMSIVEEFEKHISSLRLLKIEKTPDSTIYYYKDEKTGETWVVTVSKSAKKLKSSPTTIKEDPNGPRKVTITTELSPEDAKYAPIVKRLQEAAVKAFLEMRDGPLKETLDALLERSRLTGKTVSLTYLTVLEVDGEKKLFVVTVSIKVEPDGTVKISVTLSEATVSKL
>alex.naka.Venusaur
SRFSNCPRRYRGICTNSGECTYAKNLRTYTCQCVSGYTGHRCEELDIRYL
>x.rustamov.traj_9_8_model_1_0
TVTVTVTGQTEVKLNSTITLTATVTGVYLATWATFWYSQKEGEPLEFLGSIGSWGVMAYNDAYKDRLTMSRDLAAQTATIQLHNAQPEDTRTYYAGLPDFAGGAWLAHWSAGLLVKVVE
>keaun.GWFGVVFKADIAGVSEKVAIELSGGYEGSLTTPSGWNQ
GWFGVVFKADIAGVSEKVAIELSGGYEGSLTTPSGWNQ
>keaun.GWFGVVFKADIARDSEFVAILESQGYLSSITTFSGWNQ
GWFGVVFKADIARDSEFVAILESQGYLSSITTFSGWNQ
>zulfatmi.pocket1pep78
TRLGTPVYVYADYDTP
>julian.faust.BecotatugxPimurutamab_scfv
QVQLQESGPGLVKPSETLSLTCTVSGFSLTNYGVHWVRQAPGKGLEWLGVIWSGGNTDYGNEFTSRFTISRDNAKNSLYLQMNSLRAEDTAVYYCARALDYYDYEFAYWGQGTMVTVSSGGGGSGGGGSGGGGSGGGGSEIVLTQSPATLSLSPGERATLSCRASQSIGTNIHWYQQKPGQAPRLLIKYASESISGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQQNNNWPTSFGGGTKVEIK
>paulafcfranklin.synth_rosetta_9
SHFSECPEEYRHFCFHGTCRFLWLENKPACICHPGYVGARCEEADLLAVVASSRNRGP
>tiejun.wei.egfr_binder_design_208_dldesign_10_af2pred.pdb_A
KVSFNNSEEARQLILDETEGRLETRRLDILYKDKTLEEKVEARKAEIEAA
>salireza111.Seq166_7_003_9
MVDLLVHRAKAEGNPVEIIEKELGSGIIERTAIAGIGGTTAVATELVPA
>qilin_y.test4
GTHTLTIKKIEALDKYACSYVSDRPLTDEDIDKLMEAAKAKGYTLTVLRDLKWWEKYIFKAKAKPDLKSVTITID
>joaosartori2.c3
SHFTPCPETHRGFCFHGTCRYLVDVAAPSCVCHSGYYGARCEHADLKSDVALLLLLLL
>AmirM.MHosseini.seq4
NLPGTCPPSHDGYCKHGGTCYYIPALNKYACNCVVGYIGERCQYRDEAYAAKK
>aswini.seed1_1
LSRSICPSNYDSYCLNGGQCFLAEDISGYTCMCRLGYSGRRVETFDQIYT
>biolucasmachado.engineered_binder_2
SLSVPCGPEHAGYCVHGECRHSYLLNQVSCVCHDGWTGERCELPDLLAIVVMVMVMVM
>alessio.daddio.AD_4
SPAAAAGAAQLRAAADEVRAARDETLEQMKKEGVSEEDIDDYSTLMLDTYGALLGRANAA
>biolucasmachado.engineered_binder_6
SYFTPCGPEFNGYCVHGECRYVALLNQVACICHDGWTGERCELPDLLAIVASSRNSVD
>joaosartori2.c4
SHFTRCPSTHRGFCFHGTCRFLVNEEKPPCVCHSGYRGARCEHADLHVIVALLSGLAI
>AmirM.MHosseini.seq1
PPPPVQSHFAPCPPEHAQFCFHGTCRYVVQENKPACVCHSGWVGARCEHADLLAIVAAAK
>biolucasmachado.engineered_binder_9
SLPRPCGPEDRGYCVHGTCRYSYLLNQVSCVCDDGWTGERCELPDLLAI
>antorsae.TA525_0_0
SSFLTYCLHGTPKYESSLNKWSCVCDPGWYGERCEFKDLL
>alecl.relaxedA
SFSPFRPCSPEEESFCQHGECRFDVVEQRPACLCAGGYVGARCEAVDVAV
>z_peplib.pepseq_design_8
TWTTVITILKKMDWRASEMMNVATAVTINEMGIVRKQNVIEAGSEIKSAV
>revoli.mutated_nAb_5
QVILEESGGGVVQTGGWLRLTCAASGRTSRSYGMGWFRQMPGRERQFVSGISWRGDSTGYADMVKGRFYISRDNALNTVQLQMNWLKPEDTAIYYCAAAAGSAWYGTLYEYDYWGQGTQVTV
>duynth29.Duy_L111_mpnn14
ALSPLVQLTLEAAKNNMSWQEWMHKIRPLVDDYTNINVIMALHMLRHLAVIVRALNDGDLEELAREIALAEEQWAADQILVKAGYGHPDDPFYKVGEEAMAIIREIAAEHV
>jakublala.epitope_1_30aa.pdb
MPPDQVRYEHRQQLEDAVQAFMRQQKMENE
>hughy.7om4_B_A_180_rnd1_v1_full
QVQLQESGGGLVQPGGSLRLSCAASGSIFSTYAMGWYRQAPGKQRELVAAISNGGSINYADSVKGRFTISRDNSKNAVDLQMDSLRPEDTAVYYCAADRTIASIIRREYAYWGQGTQVTVSS
>alex.naka.Blastoise
ELFSRCPKRYHGICGNNGQCRYAINLRTYTCRCVSGYTGDRCQELDIRYLLLLN
>alex.naka.Wartortle
SLFRRCPARYHGICGNNGQCRYAINLRTYTCRCVSGYTGPRCQELDIRYLLLLN
>zhoup1366.DBZ6___A
QVQLVESGGGLVQPGGSLRLSCAASGFDLGGYSLGWFRQAPGQGLEAVAAINWNGGNTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARSYYYGGFGMDYWGQGTLVTVS

**Explode just like in the large data set**

In [6]:
import json

df2["evaluations"] = df2["evaluations"].apply(json.loads)

# print(type(alldata.loc[0, "evaluations"]))

df_metrics = df2.explode("evaluations", ignore_index=True)
df_metrics = df_metrics.join(pd.json_normalize(df_metrics.pop("evaluations")))
df_metrics

,id,name,sequence,author,designMethod,type,metric,target,valueType,value.url,value,unit
0,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,bli_kinetic_curves,egfr,json,https://proteinbase-pub.t3.storage.dev/kinetic...,NaN,NaN
1,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,binding,egfr,boolean,NaN,False,NaN
2,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,binding,egfr,boolean,NaN,False,NaN
3,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,expressed,NaN,boolean,NaN,True,NaN
4,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,binding_strength,egfr,label,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
17566,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,proteinmpnn_score,NaN,numeric,NaN,1.508,NaN
17567,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,redesigned_proteinmpnn_score,NaN,numeric,NaN,0.99379,NaN
17568,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,proteinmpnn_seq_recovery,NaN,numeric,NaN,0.48792,%
17569,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,esmfold_structure_prediction,NaN,json,https://proteinbase-pub.t3.storage.dev/01K6H2G...,NaN,NaN
17570,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,esmfold_stylized_image,NaN,json,https://proteinbase-pub.t3.storage.dev/01K6H2G...,NaN,NaN

**Drop irrelevant columns**

In [7]:
def drop_columns(df, columns):
    """
    Drop the specified columns from a pandas dataframe.
    """
    return df.drop(columns=columns, axis=1, errors='ignore')

columns_to_drop = ['value.url']
df_metrics = drop_columns(df_metrics, columns_to_drop)
df_metrics

,id,name,sequence,author,designMethod,type,metric,target,valueType,value,unit
0,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,bli_kinetic_curves,egfr,json,NaN,NaN
1,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,binding,egfr,boolean,False,NaN
2,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,binding,egfr,boolean,False,NaN
3,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,expressed,NaN,boolean,True,NaN
4,violet-shark-wave,antorsae.TA_4_4,TYCLHGTPVYISSLNKWSCVCDKGWYGERCEF,antorsae,NaN,experimental,binding_strength,egfr,label,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...
17566,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,proteinmpnn_score,NaN,numeric,1.508,NaN
17567,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,redesigned_proteinmpnn_score,NaN,numeric,0.99379,NaN
17568,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,proteinmpnn_seq_recovery,NaN,numeric,0.48792,%
17569,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,esmfold_structure_prediction,NaN,json,NaN,NaN
17570,scarlet-ram-clay,niklas.95B59203-B642-4754-BCD3-8E670A722C8D_l9...,AAPEPSEIEKLLEKAFEYLDKLLPVYEAEDLSEETKNYIFLSIART...,convexity-labs,NaN,computational,esmfold_stylized_image,NaN,json,NaN,NaN

**Make a pivot table and export to CSV**

In [31]:
df_metrics["designMethod"] = df_metrics["designMethod"].fillna("Unknown")
subset_pivot = df_metrics.pivot_table(index=["name", "id", "designMethod", "sequence"], columns="metric", values="value", aggfunc="first").reset_index()
subset_pivot.columns.name = None
subset_pivot
# subset_pivot.to_csv('contest_2_round_2_metrics_summary.csv', index=False)

,name,id,designMethod,sequence,aligned-lengthafdb50,aligned-lengthcath50,aligned-lengthpdb100,binding,binding_strength,cath_detail,...,rmsdafdb50,rmsdcath50,rmsdpdb100,seqidentityafdb50,seqidentitycath50,seqidentitypdb100,ted_confidence,tm-scoreafdb50,tm-scorecath50,tm-scorepdb100
0,724928537.DBZ6 | A,mellow-cat-birch,Unknown,QVQLVESGGGLVQPGGSLRLSCAASGRTFSSYALGWFRQAPGQGLE...,108,100,112,False,None,Sandwich,...,0.96,2.41,0.82,74.7,70.7,75.6,2,0.92848,0.74337,0.96424
1,724928537.DBZ7 | A,rough-bat-willow,Unknown,QVQLVESGGGLVQPGGSLRLSCAASGYTFTEYPLGWFRQAPGQGLE...,99,93,103,False,None,Sandwich,...,1.21,2.45,1.11,80.6,73.2,81.4,2,0.91914,0.72739,0.93867
2,724928537.DBZ8 | A,wild-raven-granite,Unknown,QVQLVESGGGLVQPGGSLRLSCAASGFSLTVYGLGWFRQAPGQGLE...,116,102,113,False,None,Sandwich,...,1.31,2.06,0.82,69.4,71.7,73.9,2,0.95274,0.76052,0.94269
3,Ali.RASOULI.intern.model_77_142_3,shy-lion-ice,Unknown,DEGIENFVNFMKKSQEMMKGNDEERREWHAWMRVMLEKSTNKDMTE...,64,35,45,False,None,Up Down Bundle,...,2.36,3.35,3.19,23.4,20.6,19.2,2,0.67038,0.35974,0.45335
4,AmirM.MHosseini.seq1,mellow-tiger-lotus,Unknown,PPPPVQSHFAPCPPEHAQFCFHGTCRYVVQENKPACVCHSGWVGAR...,51,40,40,False,None,Ribbon,...,1.05,2.81,2.94,76,79.5,79.5,2,0.87019,0.39701,0.3851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,zhoup1366.DBZ7 | A,silent-crow-ice,Unknown,QVQLVESGGGLVQPGGSLRLSCAASGFTFSSYALGWFRQAPGQGLE...,106,99,109,False,None,Sandwich,...,0.77,2.44,0.93,74,76.8,83.3,2,0.94625,0.74406,0.96183
396,zhoup1366.DBZ8 | A,rapid-falcon-reed,Unknown,QVQLVESGGGLVQPGGSLRLSCAASGFSLTFYSLGWFRQAPGQGLE...,115,102,113,False,None,Sandwich,...,0.81,2.07,0.77,70.3,71.7,72.8,2,0.96821,0.76572,0.95192
397,zulfatmi.pocket1pep78,young-cat-rose,Unknown,TRLGTPVYVYADYDTP,NaN,NaN,NaN,False,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,zulfatmi.pocket2pep63,deep-deer-granite,Unknown,TPPDTRIYESRLRQYGS,NaN,NaN,NaN,False,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,zulfatmi.pocket7pep42,vast-mole-flint,Unknown,ATPYGTPASAYRK,NaN,NaN,NaN,False,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN